FROM php:8.2-fpm

WORKDIR /var/www/html

COPY --from=composer:2.5.5 /usr/bin/composer /usr/local/bin/composer

RUN apt-get update \
    && apt-get install -y libmcrypt-dev \
    && apt-get install -y libzip-dev \
    && apt-get install -y libpq-dev \
    && apt-get install -y libmagickwand-dev \
    && apt-get install -y libmagickcore-dev \
    && apt-get install -y imagemagick \
    && apt-get install -y libzip-dev \
    && apt-get install -y libwebp-dev \
    && pecl install imagick \

RUN docker-php-ext-install zip \
    && docker-php-ext-install bcmath \
    && docker-php-ext-install intl \
    && docker-php-ext-install pdo \
    && docker-php-ext-install zip \
    && docker-php-ext-install exif \
    && docker-php-ext-install opcache \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
        && docker-php-ext-configure mysqli --with-mysqli=mysqlnd \
        && docker-php-ext-install pdo_mysql \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
        && docker-php-ext-install pgsql pdo_pgsql \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
        && docker-php-ext-install gd \
    && docker-php-ext-enable imagick \
    && PHP_OPENSSL=yes
